export enum PIZZA_FRENZY_TOPPING_UPGRADE {
  BRONZE = 1, SILVER, GOLD, PLATINUM
}

export enum TRANSJAKARTA_DIRECTION {
  NORTH_SOUTH = "NS",
  SOUTH_NORTH = "SN"
}

export enum FOUR_PC_HARVESTABLE_RARITY {
  NO_RARITY,
  COMMON,
  UNCOMMON,
  RARE
}