import type { Metadata } from "next";
import { PT_Sans, Inconsolata } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from "@mui/material/styles";
import { themeOptions } from "@/theme";
import classNames from "classnames";
import { ClerkProvider } from '@clerk/nextjs';

import "./globals.css";

const ptSansFont = PT_Sans({ weight: ['400', '700'], subsets: ['latin'], display: 'swap' });
const inconsolata = Inconsolata({ weight: ['400', '700'], subsets: ['latin'], display: 'swap' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
        </head>
        <body className={classNames(ptSansFont.className, inconsolata.className)}>
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <ThemeProvider theme={themeOptions}>
              {children}
            </ThemeProvider>
          </AppRouterCacheProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
