import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import "./post.css";
import { Flowbite } from "flowbite-react";

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={montserrat.className}>
        <Flowbite theme={{mode: 'dark'}}>
          {children}
        </Flowbite>
      </body>
    </html>
  );
}
