/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as noHeaderLoginRouteImport } from './routes/(no-header)/login'
import { Route as headerHeaderRouteRouteImport } from './routes/(header)/_header/route'
import { Route as headerHeaderIndexRouteImport } from './routes/(header)/_header/index'
import { Route as headerHeaderDashboardRouteImport } from './routes/(header)/_header/dashboard'
import { Route as headerHeaderHaydayIndexRouteImport } from './routes/(header)/_header/hayday/index'
import { Route as headerHeaderExportIndexRouteImport } from './routes/(header)/_header/export/index'
import { Route as headerHeaderCygnusIndexRouteImport } from './routes/(header)/_header/cygnus/index'
import { Route as headerHeaderHaydayProductIndexRouteImport } from './routes/(header)/_header/hayday/product.index'
import { Route as headerHeaderCygnusCropIndexRouteImport } from './routes/(header)/_header/cygnus/crop/index'
import { Route as headerHeaderHaydayProductIdRouteImport } from './routes/(header)/_header/hayday/product.$id'
import { Route as headerHeaderCygnusCropIdRouteImport } from './routes/(header)/_header/cygnus/crop/$id'
import { Route as headerHeaderExportCategoryDataTypeRouteImport } from './routes/(header)/_header/export/$category.$data.$type'

const noHeaderLoginRoute = noHeaderLoginRouteImport.update({
  id: '/(no-header)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const headerHeaderRouteRoute = headerHeaderRouteRouteImport.update({
  id: '/(header)/_header',
  getParentRoute: () => rootRouteImport,
} as any)
const headerHeaderIndexRoute = headerHeaderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => headerHeaderRouteRoute,
} as any)
const headerHeaderDashboardRoute = headerHeaderDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => headerHeaderRouteRoute,
} as any)
const headerHeaderHaydayIndexRoute = headerHeaderHaydayIndexRouteImport.update({
  id: '/hayday/',
  path: '/hayday/',
  getParentRoute: () => headerHeaderRouteRoute,
} as any)
const headerHeaderExportIndexRoute = headerHeaderExportIndexRouteImport.update({
  id: '/export/',
  path: '/export/',
  getParentRoute: () => headerHeaderRouteRoute,
} as any)
const headerHeaderCygnusIndexRoute = headerHeaderCygnusIndexRouteImport.update({
  id: '/cygnus/',
  path: '/cygnus/',
  getParentRoute: () => headerHeaderRouteRoute,
} as any)
const headerHeaderHaydayProductIndexRoute =
  headerHeaderHaydayProductIndexRouteImport.update({
    id: '/hayday/product/',
    path: '/hayday/product/',
    getParentRoute: () => headerHeaderRouteRoute,
  } as any)
const headerHeaderCygnusCropIndexRoute =
  headerHeaderCygnusCropIndexRouteImport.update({
    id: '/cygnus/crop/',
    path: '/cygnus/crop/',
    getParentRoute: () => headerHeaderRouteRoute,
  } as any)
const headerHeaderHaydayProductIdRoute =
  headerHeaderHaydayProductIdRouteImport.update({
    id: '/hayday/product/$id',
    path: '/hayday/product/$id',
    getParentRoute: () => headerHeaderRouteRoute,
  } as any)
const headerHeaderCygnusCropIdRoute =
  headerHeaderCygnusCropIdRouteImport.update({
    id: '/cygnus/crop/$id',
    path: '/cygnus/crop/$id',
    getParentRoute: () => headerHeaderRouteRoute,
  } as any)
const headerHeaderExportCategoryDataTypeRoute =
  headerHeaderExportCategoryDataTypeRouteImport.update({
    id: '/export/$category/$data/$type',
    path: '/export/$category/$data/$type',
    getParentRoute: () => headerHeaderRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof noHeaderLoginRoute
  '/dashboard': typeof headerHeaderDashboardRoute
  '/': typeof headerHeaderIndexRoute
  '/cygnus': typeof headerHeaderCygnusIndexRoute
  '/export': typeof headerHeaderExportIndexRoute
  '/hayday': typeof headerHeaderHaydayIndexRoute
  '/cygnus/crop/$id': typeof headerHeaderCygnusCropIdRoute
  '/hayday/product/$id': typeof headerHeaderHaydayProductIdRoute
  '/cygnus/crop': typeof headerHeaderCygnusCropIndexRoute
  '/hayday/product': typeof headerHeaderHaydayProductIndexRoute
  '/export/$category/$data/$type': typeof headerHeaderExportCategoryDataTypeRoute
}
export interface FileRoutesByTo {
  '/login': typeof noHeaderLoginRoute
  '/dashboard': typeof headerHeaderDashboardRoute
  '/': typeof headerHeaderIndexRoute
  '/cygnus': typeof headerHeaderCygnusIndexRoute
  '/export': typeof headerHeaderExportIndexRoute
  '/hayday': typeof headerHeaderHaydayIndexRoute
  '/cygnus/crop/$id': typeof headerHeaderCygnusCropIdRoute
  '/hayday/product/$id': typeof headerHeaderHaydayProductIdRoute
  '/cygnus/crop': typeof headerHeaderCygnusCropIndexRoute
  '/hayday/product': typeof headerHeaderHaydayProductIndexRoute
  '/export/$category/$data/$type': typeof headerHeaderExportCategoryDataTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(header)/_header': typeof headerHeaderRouteRouteWithChildren
  '/(no-header)/login': typeof noHeaderLoginRoute
  '/(header)/_header/dashboard': typeof headerHeaderDashboardRoute
  '/(header)/_header/': typeof headerHeaderIndexRoute
  '/(header)/_header/cygnus/': typeof headerHeaderCygnusIndexRoute
  '/(header)/_header/export/': typeof headerHeaderExportIndexRoute
  '/(header)/_header/hayday/': typeof headerHeaderHaydayIndexRoute
  '/(header)/_header/cygnus/crop/$id': typeof headerHeaderCygnusCropIdRoute
  '/(header)/_header/hayday/product/$id': typeof headerHeaderHaydayProductIdRoute
  '/(header)/_header/cygnus/crop/': typeof headerHeaderCygnusCropIndexRoute
  '/(header)/_header/hayday/product/': typeof headerHeaderHaydayProductIndexRoute
  '/(header)/_header/export/$category/$data/$type': typeof headerHeaderExportCategoryDataTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/dashboard'
    | '/'
    | '/cygnus'
    | '/export'
    | '/hayday'
    | '/cygnus/crop/$id'
    | '/hayday/product/$id'
    | '/cygnus/crop'
    | '/hayday/product'
    | '/export/$category/$data/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/'
    | '/cygnus'
    | '/export'
    | '/hayday'
    | '/cygnus/crop/$id'
    | '/hayday/product/$id'
    | '/cygnus/crop'
    | '/hayday/product'
    | '/export/$category/$data/$type'
  id:
    | '__root__'
    | '/(header)/_header'
    | '/(no-header)/login'
    | '/(header)/_header/dashboard'
    | '/(header)/_header/'
    | '/(header)/_header/cygnus/'
    | '/(header)/_header/export/'
    | '/(header)/_header/hayday/'
    | '/(header)/_header/cygnus/crop/$id'
    | '/(header)/_header/hayday/product/$id'
    | '/(header)/_header/cygnus/crop/'
    | '/(header)/_header/hayday/product/'
    | '/(header)/_header/export/$category/$data/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  headerHeaderRouteRoute: typeof headerHeaderRouteRouteWithChildren
  noHeaderLoginRoute: typeof noHeaderLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(no-header)/login': {
      id: '/(no-header)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof noHeaderLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(header)/_header': {
      id: '/(header)/_header'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof headerHeaderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(header)/_header/': {
      id: '/(header)/_header/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof headerHeaderIndexRouteImport
      parentRoute: typeof headerHeaderRouteRoute
    }
    '/(header)/_header/dashboard': {
      id: '/(header)/_header/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof headerHeaderDashboardRouteImport
      parentRoute: typeof headerHeaderRouteRoute
    }
    '/(header)/_header/hayday/': {
      id: '/(header)/_header/hayday/'
      path: '/hayday'
      fullPath: '/hayday'
      preLoaderRoute: typeof headerHeaderHaydayIndexRouteImport
      parentRoute: typeof headerHeaderRouteRoute
    }
    '/(header)/_header/export/': {
      id: '/(header)/_header/export/'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof headerHeaderExportIndexRouteImport
      parentRoute: typeof headerHeaderRouteRoute
    }
    '/(header)/_header/cygnus/': {
      id: '/(header)/_header/cygnus/'
      path: '/cygnus'
      fullPath: '/cygnus'
      preLoaderRoute: typeof headerHeaderCygnusIndexRouteImport
      parentRoute: typeof headerHeaderRouteRoute
    }
    '/(header)/_header/hayday/product/': {
      id: '/(header)/_header/hayday/product/'
      path: '/hayday/product'
      fullPath: '/hayday/product'
      preLoaderRoute: typeof headerHeaderHaydayProductIndexRouteImport
      parentRoute: typeof headerHeaderRouteRoute
    }
    '/(header)/_header/cygnus/crop/': {
      id: '/(header)/_header/cygnus/crop/'
      path: '/cygnus/crop'
      fullPath: '/cygnus/crop'
      preLoaderRoute: typeof headerHeaderCygnusCropIndexRouteImport
      parentRoute: typeof headerHeaderRouteRoute
    }
    '/(header)/_header/hayday/product/$id': {
      id: '/(header)/_header/hayday/product/$id'
      path: '/hayday/product/$id'
      fullPath: '/hayday/product/$id'
      preLoaderRoute: typeof headerHeaderHaydayProductIdRouteImport
      parentRoute: typeof headerHeaderRouteRoute
    }
    '/(header)/_header/cygnus/crop/$id': {
      id: '/(header)/_header/cygnus/crop/$id'
      path: '/cygnus/crop/$id'
      fullPath: '/cygnus/crop/$id'
      preLoaderRoute: typeof headerHeaderCygnusCropIdRouteImport
      parentRoute: typeof headerHeaderRouteRoute
    }
    '/(header)/_header/export/$category/$data/$type': {
      id: '/(header)/_header/export/$category/$data/$type'
      path: '/export/$category/$data/$type'
      fullPath: '/export/$category/$data/$type'
      preLoaderRoute: typeof headerHeaderExportCategoryDataTypeRouteImport
      parentRoute: typeof headerHeaderRouteRoute
    }
  }
}

interface headerHeaderRouteRouteChildren {
  headerHeaderDashboardRoute: typeof headerHeaderDashboardRoute
  headerHeaderIndexRoute: typeof headerHeaderIndexRoute
  headerHeaderCygnusIndexRoute: typeof headerHeaderCygnusIndexRoute
  headerHeaderExportIndexRoute: typeof headerHeaderExportIndexRoute
  headerHeaderHaydayIndexRoute: typeof headerHeaderHaydayIndexRoute
  headerHeaderCygnusCropIdRoute: typeof headerHeaderCygnusCropIdRoute
  headerHeaderHaydayProductIdRoute: typeof headerHeaderHaydayProductIdRoute
  headerHeaderCygnusCropIndexRoute: typeof headerHeaderCygnusCropIndexRoute
  headerHeaderHaydayProductIndexRoute: typeof headerHeaderHaydayProductIndexRoute
  headerHeaderExportCategoryDataTypeRoute: typeof headerHeaderExportCategoryDataTypeRoute
}

const headerHeaderRouteRouteChildren: headerHeaderRouteRouteChildren = {
  headerHeaderDashboardRoute: headerHeaderDashboardRoute,
  headerHeaderIndexRoute: headerHeaderIndexRoute,
  headerHeaderCygnusIndexRoute: headerHeaderCygnusIndexRoute,
  headerHeaderExportIndexRoute: headerHeaderExportIndexRoute,
  headerHeaderHaydayIndexRoute: headerHeaderHaydayIndexRoute,
  headerHeaderCygnusCropIdRoute: headerHeaderCygnusCropIdRoute,
  headerHeaderHaydayProductIdRoute: headerHeaderHaydayProductIdRoute,
  headerHeaderCygnusCropIndexRoute: headerHeaderCygnusCropIndexRoute,
  headerHeaderHaydayProductIndexRoute: headerHeaderHaydayProductIndexRoute,
  headerHeaderExportCategoryDataTypeRoute:
    headerHeaderExportCategoryDataTypeRoute,
}

const headerHeaderRouteRouteWithChildren =
  headerHeaderRouteRoute._addFileChildren(headerHeaderRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  headerHeaderRouteRoute: headerHeaderRouteRouteWithChildren,
  noHeaderLoginRoute: noHeaderLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
